name: Deliang app containerization pipeline 
# Trigger -- when this pipeline should start
on:
  push:
    branches:
      - "dev"

# creating multiple jobs
jobs:
  del-code-checkjob:
    runs-on: ubuntu-latest
    steps:
      - name: checking only 
        run: | 
          echo "just checking"
          whoami 

  del-sast-job:
    runs-on: self-hosted
    needs: del-code-checkjob # it will wait for job1 to finis 
    steps:
      - name: pwd and whoami
        run: |
          pwd  
          whoami 
      - name: using upload artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: ashu-artifact
          path: |
            . 
            !**/.git*
            !**/*.md 
  del-build-job:
    runs-on: ubuntu-latest
    needs: del-sast-job # it will wait for SAST job to finish
    steps:
      - name: just check general message
        run: |
          echo "docker related details "
          docker version 
          docker-compose version
      - name: downloading artifacts 
        uses: actions/download-artifact@v4
        with:
          name: ashu-artifact
          path: . 
      - name: docker compose to build and test
        run: |
          ls -a 
          docker-compose up -d --build 
          sleep 2
          docker-compose ps 
      - name: verify health check page by access it usign postman / curl 
        run: |
          echo  "access health.html page using curl "
          curl -f  http://localhost:1234/health.html