name: Deliang app containerization pipeline 
# Trigger -- when this pipeline should start
on:
  push:
    branches:
      - "dev"

# creating multiple jobs
jobs:
  del-code-checkjob:
    runs-on: ubuntu-latest
    steps:
      - name: checking only 
        run: | 
          echo "just checking"
          whoami 

  del-sast-job:
    runs-on: self-hosted
    needs: del-code-checkjob # it will wait for job1 to finis 
    steps:
      - name: pwd and whoami
        run: |
          pwd  
          whoami 
  del-build-job:
    runs-on: macos-latest
    needs: del-sast-job # it will wait for SAST job to finish
    steps:
      - name: just check general message
        run: |
          echo "python version checking"
          python -V