# create pipeline with some name 
name: Deliang app containerization pipeline 
# Trigger -- when this pipeline should start
on:
  push:
    branches:
      - "dev"

# jobs for performing operatiosn 
jobs:
  deliang-image-build:
    runs-on: ubuntu-latest
    # this server will be provision by github backen for this job
    steps:
      - name: run some basic commands on above server to do some verify 
        run: |
          uname -r 
          whoami
          cat /etc/os-release 
          docker version 
          docker-compose version 
      - name: using pre-design github workflow to get copy gitrepo code to runners machine 
        uses: actions/checkout@v4 

      - name: verify github code and use docker compose to build and create 
        run: |
          ls  -a 
          docker-compose  up -d  
          sleep 2 
          docker-compose ps 
      - name: verify health check page by access it usign postman / curl 
        run: |
          echo  "access health.html page using curl "
          curl -f  http://localhost:1234/health.html
          # here we will get http response code 200 

      #- name: try to login from runner to docker hub account
       # run: |
        #  docker login -u delianghan -p Hello@123
         # docker tag delianghan:v1 docker.io/deliang:v1
          # above command to make an alias of image to docker hub format
          #docker push docker.io/deliang:v1
          #docker logout

      - name: try to login from runner to docker hub account 
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to docker hub 
        uses: docker/build-push-action@v5
        with:
          context: . # location of Dockerfile 
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/deliang:v1

      - name: docker logout from runner after pushing image 
        run: docker logout 

          

